spring.servlet.multipart.max-file-size: 10MB
spring.servlet.multipart.max-request-size: 10MB
spring.http.multipart.enabled: false

server.port: 5000
aws.s3:
  bucketName: copy-pasta-data
  pollingIntervalMs: 5000
  pollingRetries: 18

recaptcha:
  apiUrl: "https://www.google.com/recaptcha/api/siteverify"
  secret: ${RECAPTCHA_SECRET}
  scoreThreshold: 0.5
