spring.servlet.multipart.max-file-size: 10MB
spring.servlet.multipart.max-request-size: 10MB
spring.http.multipart.enabled: false

amazonProperties:
    region: eu-west-1
    accessKey: ${S3_ACCESS_KEY:dummy}
    secretKey: ${S3_SECRET_KEY:dummy}
    bucketName: copy-pasta-data
