spring.servlet.multipart.max-file-size: 10MB
spring.servlet.multipart.max-request-size: 10MB
spring.http.multipart.enabled: false

server.port: 5000
aws.s3:
  bucketName: copy-pasta-data
  pollingIntervalMs: 3000
  pollingRetries: 20
